using Blazored.SessionStorage;
using BlzSinhVien.Client;
using BlzSinhVien.Client.Authentication;
using BlzSinhVien.Client.Service.ChucVuService;
using BlzSinhVien.Client.Service.GiaoVienService;
using BlzSinhVien.Client.Service.KhoaHocService;
using BlzSinhVien.Client.Service.LopHocService;
using BlzSinhVien.Client.Service.NganhHocService;
using BlzSinhVien.Client.Service.SinhVienService;
using BlzSinhVien.Client.Service.UserService;
using BlzSinhVien.Client.Service.MonHocService;
using BlzSinhVien.Shared.Model.User;
using Microsoft.AspNetCore.Components.Authorization;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor.Services;
using BlzSinhVien.Client.Service.HocKyService;
using BlzSinhVien.Client.Service.ImageService;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");

builder.Services.AddScoped(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });

builder.Services.AddScoped<AuthenticationStateProvider, CustomAuthenticationStateProvider>();
builder.Services.AddBlazoredSessionStorage();
builder.Services.AddMudServices();
builder.Services.AddAuthorizationCore();
builder.Services.AddScoped<ISinhVienService, SinhVienService>();
builder.Services.AddScoped<ILopHocService, LopHocService>();
builder.Services.AddScoped<IUserService, UserService>();
builder.Services.AddScoped<IChucVuService, ChucVuService>();
builder.Services.AddScoped<IGiaoVienService, GiaoVienService>();
builder.Services.AddScoped<IKhoaHocService, KhoaHocService>();
builder.Services.AddScoped<INganhHocService, NganhHocService>();
builder.Services.AddSingleton<BLUserSession>();
builder.Services.AddScoped<IMonHocKhoaService, MonHocKhoaService>();
builder.Services.AddScoped<IMonHocNganhService, MonHocNganhService>();
builder.Services.AddScoped<IMonHocService, MonHocService>();
builder.Services.AddScoped<IHocKyService, HocKyService>();
builder.Services.AddScoped<IImageService, ImageService>();
await builder.Build().RunAsync();
